-- ============================================================
-- IDP Auth Service - Oracle DDL (Flyway Migration V1)
-- ============================================================

-- 사용자 테이블
CREATE TABLE USERS (
    ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME    VARCHAR2(100)   NOT NULL,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    EMAIL       VARCHAR2(200)   NOT NULL,
    ENABLED     NUMBER(1)       DEFAULT 1 NOT NULL,
    LOCKED      NUMBER(1)       DEFAULT 0 NOT NULL,
    CREATED_AT  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UQ_USERS_USERNAME UNIQUE (USERNAME),
    CONSTRAINT UQ_USERS_EMAIL    UNIQUE (EMAIL)
);

-- 역할 테이블
CREATE TABLE ROLES (
    ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME        VARCHAR2(100)   NOT NULL,
    DESCRIPTION VARCHAR2(500),
    CREATED_AT  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UQ_ROLES_NAME UNIQUE (NAME)
);

-- 권한 테이블 (리소스 + HTTP 메서드)
CREATE TABLE PERMISSIONS (
    ID               NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RESOURCE_PATTERN VARCHAR2(500)  NOT NULL,
    ACTION           VARCHAR2(20)   NOT NULL,  -- GET, POST, PUT, DELETE, PATCH, *
    DESCRIPTION      VARCHAR2(500),
    CREATED_AT       TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UQ_PERMISSIONS UNIQUE (RESOURCE_PATTERN, ACTION)
);

-- 사용자-역할 매핑 (N:M)
CREATE TABLE USER_ROLES (
    USER_ID  NUMBER NOT NULL,
    ROLE_ID  NUMBER NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT FK_USER_ROLES_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_USER_ROLES_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID) ON DELETE CASCADE
);

-- 역할-권한 매핑 (N:M)
CREATE TABLE ROLE_PERMISSIONS (
    ROLE_ID       NUMBER NOT NULL,
    PERMISSION_ID NUMBER NOT NULL,
    PRIMARY KEY (ROLE_ID, PERMISSION_ID),
    CONSTRAINT FK_ROLE_PERM_ROLE FOREIGN KEY (ROLE_ID)       REFERENCES ROLES(ID)       ON DELETE CASCADE,
    CONSTRAINT FK_ROLE_PERM_PERM FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSIONS(ID) ON DELETE CASCADE
);

-- Refresh Token 테이블 (1회용 Rotation)
CREATE TABLE REFRESH_TOKENS (
    ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    JTI         VARCHAR2(36)    NOT NULL,
    USER_ID     NUMBER          NOT NULL,
    TOKEN_HASH  VARCHAR2(255)   NOT NULL,
    ISSUED_AT   TIMESTAMP       NOT NULL,
    EXPIRES_AT  TIMESTAMP       NOT NULL,
    REVOKED     NUMBER(1)       DEFAULT 0 NOT NULL,
    REVOKED_AT  TIMESTAMP,
    CONSTRAINT UQ_REFRESH_TOKENS_JTI UNIQUE (JTI),
    CONSTRAINT FK_REFRESH_TOKENS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- Access Token 블랙리스트 (로그아웃/강제 만료된 JTI)
CREATE TABLE TOKEN_BLACKLIST (
    ID         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    JTI        VARCHAR2(36)  NOT NULL,
    USER_ID    NUMBER,
    EXPIRES_AT TIMESTAMP     NOT NULL,
    CREATED_AT TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UQ_TOKEN_BLACKLIST_JTI UNIQUE (JTI)
);

-- 감사 로그 테이블
CREATE TABLE AUDIT_LOGS (
    ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EVENT_TYPE  VARCHAR2(100) NOT NULL,
    USER_ID     NUMBER,
    USERNAME    VARCHAR2(100),
    IP_ADDRESS  VARCHAR2(50),
    USER_AGENT  VARCHAR2(500),
    RESOURCE    VARCHAR2(500),
    DETAIL      VARCHAR2(2000),
    SUCCESS     NUMBER(1)    DEFAULT 1 NOT NULL,
    CREATED_AT  TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL
);

-- 인덱스
CREATE INDEX IDX_USERS_USERNAME        ON USERS(USERNAME);
CREATE INDEX IDX_REFRESH_TOKENS_USER   ON REFRESH_TOKENS(USER_ID);
CREATE INDEX IDX_REFRESH_TOKENS_JTI    ON REFRESH_TOKENS(JTI);
CREATE INDEX IDX_TOKEN_BLACKLIST_JTI   ON TOKEN_BLACKLIST(JTI);
CREATE INDEX IDX_TOKEN_BLACKLIST_EXP   ON TOKEN_BLACKLIST(EXPIRES_AT);
CREATE INDEX IDX_AUDIT_LOGS_USER_ID    ON AUDIT_LOGS(USER_ID);
CREATE INDEX IDX_AUDIT_LOGS_CREATED_AT ON AUDIT_LOGS(CREATED_AT);

-- 기본 ADMIN 역할 삽입
INSERT INTO ROLES (NAME, DESCRIPTION) VALUES ('ROLE_ADMIN', '시스템 관리자');
INSERT INTO ROLES (NAME, DESCRIPTION) VALUES ('ROLE_USER',  '일반 사용자');

COMMIT;
